# Generated by Django 5.0 on 2023-12-07 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Apothiki",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("onoma", models.CharField(max_length=100, null=True)),
                ("perigrafi", models.CharField(max_length=200, null=True)),
                ("simioseis", models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Paraliptis",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("onoma", models.CharField(max_length=150)),
                ("monada", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="Proion",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("onoma", models.CharField(max_length=100)),
                ("seriakos_arithmos", models.CharField(max_length=100)),
                ("perigrafi", models.CharField(max_length=200, null=True)),
                (
                    "typos_proiontos",
                    models.CharField(
                        choices=[
                            ("Router", "Router"),
                            ("Switch", "Switch"),
                            ("Crypto Device", "Crypto Device"),
                        ],
                        max_length=15,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Paragelia",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "onoma_paralipti",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("perigrafi", models.CharField(max_length=200, null=True)),
                (
                    "dimiourgos",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "monada_paralipti",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="ylika_app.paraliptis",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PliroforiesParagellias",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("posotita", models.IntegerField(default=1)),
                ("imerominia", models.DateTimeField(auto_now=True)),
                ("plirofories", models.CharField(max_length=200, null=True)),
                (
                    "apothiki",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ylika_app.apothiki",
                    ),
                ),
                (
                    "paragelia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ylika_app.paragelia",
                    ),
                ),
                (
                    "proion",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ylika_app.proion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Apothema",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("posotita", models.IntegerField(default=1)),
                ("simioseis", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "apothiki",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ylika_app.apothiki",
                    ),
                ),
                (
                    "proion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ylika_app.proion",
                    ),
                ),
            ],
        ),
    ]
