# Generated by Django 5.0 on 2024-01-15 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ylika_app', '0002_proion_xrisi_alter_proion_typos_proiontos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proion',
            name='xrisi',
            field=models.CharField(choices=[('ΔΙΔΕΣ ΔΙΚΤΥΑΚΟΣ ΕΞΟΠΛΙΣΜΟΣ', 'ΔΙΔΕΣ ΔΙΚΤΥΑΚΟΣ ΕΞΟΠΛΙΣΜΟΣ'), ('ΣΔΑ ΠΥΡΣΕΙΑ', 'ΣΔΑ ΠΥΡΣΕΙΑ'), ('ΕΨΑΔ-ΤΗΛΕΦΩΝΙΚΟ ΚΕΝΤΡΟ', 'ΕΨΑΔ-ΤΗΛΕΦΩΝΙΚΟ ΚΕΝΤΡΟ'), ('ΚΡΥΠΤΟ', 'ΚΡΥΠΤΟ'), ('UPS', 'UPS'), ('ΛΟΙΠΑ ΥΛΙΚΑ', 'ΛΟΙΠΑ ΥΛΙΚΑ'), ('ΚΑΜΙΑ ΕΠΙΛΟΓΗ', 'ΚΑΜΙΑ ΕΠΙΛΟΓΗ')], default='ΚΑΜΙΑ ΕΠΙΛΟΓΗ', max_length=50),
        ),
    ]
