# Generated by Django 5.0 on 2024-01-19 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ylika_app', '0005_alter_apothema_imera_paralavis'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apothema',
            options={'ordering': ['-id']},
        ),
    ]
