# Generated by Django 5.0 on 2024-01-15 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ylika_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proion',
            name='xrisi',
            field=models.CharField(choices=[('ΔΡΟΜΟΛΟΓΗΤΗΣ', 'ΔΡΟΜΟΛΟΓΗΤΗΣ'), ('CONVERTER', 'CONVERTER'), ('SWITCH', 'SWITCH'), ('MODULE', 'MODULE'), ('ΜΕΤΑΤΡΟΠΕΑΣ', 'ΜΕΤΑΤΡΟΠΕΑΣ'), ('LAN EXTENDER', 'LAN EXTENDER'), ('ΚΑΛΩΔΙΩΣΗ', 'ΚΑΛΩΔΙΩΣΗ'), ('ΚΑΜΙΑ ΕΠΙΛΟΓΗ', 'ΚΑΜΙΑ ΕΠΙΛΟΓΗ')], default='ΚΑΜΙΑ ΕΠΙΛΟΓΗ', max_length=50),
        ),
        migrations.AlterField(
            model_name='proion',
            name='typos_proiontos',
            field=models.CharField(choices=[('ΔΡΟΜΟΛΟΓΗΤΗΣ', 'ΔΡΟΜΟΛΟΓΗΤΗΣ'), ('CONVERTER', 'CONVERTER'), ('SWITCH', 'SWITCH'), ('MODULE', 'MODULE'), ('ΜΕΤΑΤΡΟΠΕΑΣ', 'ΜΕΤΑΤΡΟΠΕΑΣ'), ('LAN EXTENDER', 'LAN EXTENDER'), ('ΚΑΛΩΔΙΩΣΗ', 'ΚΑΛΩΔΙΩΣΗ'), ('ΚΑΜΙΑ ΕΠΙΛΟΓΗ', 'ΚΑΜΙΑ ΕΠΙΛΟΓΗ')], default='ΚΑΜΙΑ ΕΠΙΛΟΓΗ', max_length=30),
        ),
    ]
