# Generated by Django 5.0 on 2024-01-19 08:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ylika_app', '0004_apothema_imera_paralavis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apothema',
            name='imera_paralavis',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
